/**
 * Gendrive - Default / Sample Initial Data
 * 哲生 (AI Company OS & Personal OS Engine)
 */

// =========================================================================
// 1. Initial Sample Habits
// =========================================================================

const DEFAULT_HABITS = [
  {
    id: 'H001',
    name: '朝スクワット（回数測定）',
    displayType: 'section', // 'anytime' | 'section' | 'custom'
    section: '第1セッション',
    customStart: null,
    customEnd: null,
    domain: '健康管理',
    domainMajor: 'PN3',
    dept: '品質保証部',
    deptMajor: '開発・QA',
    proj: '日常ルーティン',
    projMajor: 'プライベート',
    importance: '高',
    urgency: '中',
    mentalLoad: 2,
    physicalLoad: 4,
    frogLevel: 3,
    repeatType: '毎日',
    targetMin: 5,
    tags: ['運動', 'ルーティン'],
    status: 'uncompleted',
    createdAt: '2026-05-01T00:00:00.000Z',
    stats: { d3: 1.0, d7: 0.85, d30: 0.80, d90: 0.75, sevenDay: 0.85, thirtyDay: 0.80, ninetyDay: 0.75, tier: '🥇 Gold' }
  },
  {
    id: 'H002',
    name: '朝ジャーナル（気分・やる気・体調）',
    displayType: 'section',
    section: '第1セッション',
    customStart: null,
    customEnd: null,
    domain: 'マインド管理',
    domainMajor: 'PN3',
    dept: '秘書室',
    deptMajor: 'CEO直轄',
    proj: '日常ルーティン',
    projMajor: 'プライベート',
    importance: '高',
    urgency: '高',
    mentalLoad: 2,
    physicalLoad: 1,
    frogLevel: 2,
    repeatType: '毎日',
    targetMin: 10,
    tags: ['マインド', 'ルーティン'],
    status: 'uncompleted',
    createdAt: '2026-05-01T00:00:00.000Z',
    stats: { d3: 1.0, d7: 1.0, d30: 0.93, d90: 0.90, sevenDay: 1.0, thirtyDay: 0.93, ninetyDay: 0.90, tier: '💎 Diamond' }
  },
  {
    id: 'H003',
    name: '朝食準備と子ども送り出しサポート',
    displayType: 'section',
    section: '朝オペ',
    customStart: null,
    customEnd: null,
    domain: '育児',
    domainMajor: 'PN3',
    dept: null,
    deptMajor: null,
    proj: '日常ルーティン',
    projMajor: 'プライベート',
    importance: '高',
    urgency: '高',
    mentalLoad: 2,
    physicalLoad: 3,
    frogLevel: 2,
    repeatType: '毎日',
    targetMin: 30,
    tags: ['家事', '育児'],
    status: 'uncompleted',
    createdAt: '2026-05-01T00:00:00.000Z',
    stats: { d3: 1.0, d7: 1.0, d30: 1.0, d90: 0.95, sevenDay: 1.0, thirtyDay: 1.0, ninetyDay: 0.95, tier: '💎 Diamond' }
  },
  {
    id: 'H004',
    name: '今日やること Top3 の選定',
    displayType: 'section',
    section: '第2セッション',
    customStart: null,
    customEnd: null,
    domain: '計画運用',
    domainMajor: 'PN2',
    dept: '経営戦略部',
    deptMajor: 'CEO直轄',
    proj: 'ヒルウラ攻略',
    projMajor: 'ビジネス',
    importance: '高',
    urgency: '高',
    mentalLoad: 3,
    physicalLoad: 1,
    frogLevel: 2,
    repeatType: '毎日',
    targetMin: 5,
    tags: ['計画', 'PC作業'],
    status: 'uncompleted',
    createdAt: '2026-05-15T00:00:00.000Z',
    stats: { d3: 1.0, d7: 0.85, d30: 0.88, d90: 0.82, sevenDay: 0.85, thirtyDay: 0.88, ninetyDay: 0.82, tier: '🥇 Gold' }
  },
  {
    id: 'H005',
    name: '納品前セルフQA一次検査チェック',
    displayType: 'custom',
    section: '第3セッション',
    customStart: '13:00',
    customEnd: '17:00',
    domain: 'ビジネス (AI品質工学)',
    domainMajor: 'PN1',
    dept: '品質保証部',
    deptMajor: '開発・QA',
    proj: 'チーム構築',
    projMajor: 'ビジネス',
    importance: '高',
    urgency: '高',
    mentalLoad: 4,
    physicalLoad: 2,
    frogLevel: 4,
    repeatType: '毎日',
    targetMin: 15,
    tags: ['品質', 'ビジネス', 'PC作業'],
    status: 'uncompleted',
    createdAt: '2026-06-01T00:00:00.000Z',
    stats: { d3: 0.67, d7: 0.85, d30: 0.78, d90: 0.70, sevenDay: 0.85, thirtyDay: 0.78, ninetyDay: 0.70, tier: '🔥 Momentum' }
  },
  {
    id: 'H006',
    name: '夕食後片付けとゴミ出しルーティン',
    displayType: 'section',
    section: '夜オペ',
    customStart: null,
    customEnd: null,
    domain: '家事',
    domainMajor: 'PN3',
    dept: null,
    deptMajor: null,
    proj: '日常ルーティン',
    projMajor: 'プライベート',
    importance: '中',
    urgency: '中',
    mentalLoad: 1,
    physicalLoad: 3,
    frogLevel: 2,
    repeatType: '毎日',
    targetMin: 20,
    status: 'uncompleted',
    createdAt: '2026-05-01T00:00:00.000Z',
    stats: { d3: 1.0, d7: 0.90, d30: 0.85, d90: 0.80, sevenDay: 0.90, thirtyDay: 0.85, ninetyDay: 0.80, tier: '🥇 Gold' }
  },
  {
    id: 'H007',
    name: '夜日記（感謝3つ・今日の勝ち）',
    displayType: 'section',
    section: '第4セッション',
    customStart: null,
    customEnd: null,
    domain: 'マインド管理',
    domainMajor: 'PN3',
    dept: '秘書室',
    deptMajor: 'CEO直轄',
    proj: '日常ルーティン',
    projMajor: 'プライベート',
    importance: '高',
    urgency: '高',
    mentalLoad: 2,
    physicalLoad: 1,
    frogLevel: 1,
    repeatType: '毎日',
    targetMin: 10,
    status: 'uncompleted',
    createdAt: '2026-05-01T00:00:00.000Z',
    stats: { d3: 1.0, d7: 0.90, d30: 0.85, d90: 0.80, sevenDay: 0.90, thirtyDay: 0.85, ninetyDay: 0.80, tier: '🥇 Gold' }
  },
  {
    id: 'H008',
    name: 'こまめな水分補給 & 姿勢リセット',
    displayType: 'anytime',
    section: null,
    customStart: null,
    customEnd: null,
    domain: '健康管理',
    domainMajor: 'PN3',
    dept: null,
    deptMajor: null,
    proj: '日常ルーティン',
    projMajor: 'プライベート',
    importance: '中',
    urgency: '低',
    mentalLoad: 1,
    physicalLoad: 1,
    frogLevel: 1,
    repeatType: '毎日',
    targetMin: 1,
    status: 'uncompleted',
    createdAt: '2026-05-01T00:00:00.000Z',
    stats: { d3: 1.0, d7: 1.0, d30: 0.95, d90: 0.90, sevenDay: 1.0, thirtyDay: 0.95, ninetyDay: 0.90, tier: '💎 Diamond' }
  },
  {
    id: 'H009',
    name: '新規営業プロポーザル1件送信',
    displayType: 'section',
    section: '第2セッション',
    customStart: null,
    customEnd: null,
    domain: 'ビジネス (動画編集制作)',
    domainMajor: 'PN1',
    dept: '営業部',
    deptMajor: '営業マーケ本部',
    proj: '初案件獲得',
    projMajor: 'ビジネス',
    importance: '高',
    urgency: '高',
    mentalLoad: 4,
    physicalLoad: 1,
    frogLevel: 4,
    repeatType: '毎日',
    targetMin: 25,
    status: 'uncompleted',
    createdAt: '2026-08-01T00:00:00.000Z',
    stats: { d3: 0.67, d7: 0.71, d30: 0.45, d90: 0.22, sevenDay: 0.71, thirtyDay: 0.45, ninetyDay: 0.22, tier: '🌱 Developing' }
  },
  {
    id: 'H010',
    name: 'Obsidian ナレッジ整理・要約1本',
    displayType: 'section',
    section: '第3セッション',
    customStart: null,
    customEnd: null,
    domain: 'スキルアップ',
    domainMajor: 'PN2',
    dept: '開発部',
    deptMajor: '開発・QA',
    proj: '自己投資',
    projMajor: 'プライベート',
    importance: '中',
    urgency: '中',
    mentalLoad: 3,
    physicalLoad: 1,
    frogLevel: 3,
    repeatType: '毎日',
    targetMin: 15,
    status: 'uncompleted',
    createdAt: '2026-08-10T00:00:00.000Z',
    stats: { d3: 0.33, d7: 0.57, d30: 0.35, d90: 0.18, sevenDay: 0.57, thirtyDay: 0.35, ninetyDay: 0.18, tier: '🌱 Developing' }
  }
];

// =========================================================================
// 2. Initial Sample Tasks (GTD Buckets, Eisenhower & TaskChute Integrated)
// =========================================================================

const DEFAULT_TASKS = [
  {
    id: 'T001',
    title: '🔥 今日の最重要タスク・提案書ドラフトの作成',
    bucket: 'today',
    label: 'iron_rule',
    type: 'single',
    timingType: 'section',
    section: '第2セッション',
    customStart: null,
    customEnd: null,
    estMin: 45,
    actStart: null,
    actEnd: null,
    actMin: 0,
    frog: 4,
    domainMajor: 'PN2',
    domainMinor: 'ビジネス (動画編集制作)',
    deptMajor: 'HONBU',
    deptMinor: '企画部',
    projMajor: 'BIZ',
    projMinor: '初案件獲得',
    status: 'uncompleted',
    notes: 'テンプレAをベースに作成すること。',
    tags: ['ビジネス', 'PC作業', '重要'],
    createdAt: '2026-08-17T08:00:00.000Z'
  },
  {
    id: 'T002',
    title: '🐸 最重要カエル撃退・未読メール＆連絡の徹底処理',
    bucket: 'today',
    label: 'frog0',
    type: 'recurring',
    recurrence: { type: 'business_days' },
    timingType: 'section',
    section: '第1セッション',
    customStart: null,
    customEnd: null,
    estMin: 20,
    actStart: null,
    actEnd: null,
    actMin: 0,
    frog: 4,
    domainMajor: 'PN3',
    domainMinor: '時間効率化',
    deptMajor: 'HONBU',
    deptMinor: '企画部',
    projMajor: 'BIZ',
    projMinor: '事業継続',
    status: 'uncompleted',
    notes: 'これが終われば午前中が劇的に軽くなる！',
    tags: ['コミュニケーション', 'PC作業'],
    createdAt: '2026-08-17T05:00:00.000Z'
  },
  {
    id: 'T003',
    title: '💼 B社クライアントとの進捗確認・フィードバック反映',
    bucket: 'today',
    label: 'p1',
    type: 'single',
    timingType: 'section',
    section: '第1セッション',
    customStart: null,
    customEnd: null,
    estMin: 25,
    actStart: null,
    actEnd: null,
    actMin: 0,
    frog: 3,
    domainMajor: 'PN2',
    domainMinor: '動画編集制作',
    deptMajor: 'HONBU',
    deptMinor: '制作部',
    projMajor: 'BIZ',
    projMinor: '初案件獲得',
    status: 'uncompleted',
    notes: '',
    tags: ['ビジネス', 'クライアント'],
    createdAt: '2026-08-17T05:30:00.000Z'
  },
  {
    id: 'T004',
    title: '日用品・消耗品のAmazonまとめ発注',
    bucket: 'today',
    label: 'p3',
    type: 'single',
    timingType: 'anytime',
    section: '第3セッション',
    customStart: null,
    customEnd: null,
    estMin: 20,
    actStart: null,
    actEnd: null,
    actMin: 0,
    frog: 1,
    domainMajor: 'PN3',
    domainMinor: '生活インフラ',
    deptMajor: 'HONBU',
    deptMinor: '総務部',
    projMajor: 'LIFE',
    projMinor: '生活復旧',
    status: 'uncompleted',
    notes: '洗剤、コピー用紙、プロテイン',
    createdAt: '2026-08-17T09:00:00.000Z'
  },
  {
    id: 'T005',
    title: '🍲 夕食の買い出し・食材ストック確認',
    bucket: 'today',
    label: 'p2',
    type: 'single',
    timingType: 'section',
    section: '夜オペ',
    customStart: null,
    customEnd: null,
    estMin: 30,
    actStart: null,
    actEnd: null,
    actMin: 0,
    frog: 2,
    domainMajor: 'PN3',
    domainMinor: '家事',
    deptMajor: 'HONBU',
    deptMinor: '総務部',
    projMajor: 'LIFE',
    projMinor: '生活改善',
    status: 'uncompleted',
    notes: '野菜・卵・牛乳',
    createdAt: '2026-08-17T17:00:00.000Z'
  },
  {
    id: 'T006',
    title: '🌙 今日の勝ち3つ振り返り＆明日タスクの棚卸し',
    bucket: 'today',
    label: 'p1',
    type: 'recurring',
    recurrence: { type: 'everyday' },
    timingType: 'section',
    section: '第4セッション',
    customStart: null,
    customEnd: null,
    estMin: 15,
    actStart: null,
    actEnd: null,
    actMin: 0,
    frog: 2,
    domainMajor: 'PN1',
    domainMinor: '習慣化',
    deptMajor: 'HONBU',
    deptMinor: '経営戦略部',
    projMajor: 'LIFE',
    projMinor: '自己成長',
    status: 'uncompleted',
    notes: '',
    createdAt: '2026-08-17T21:00:00.000Z'
  },
  {
    id: 'T007',
    title: '来期に向けた新規AIサービス企画のブレスト・メモ出し',
    bucket: 'inbox',
    label: 'p2',
    type: 'single',
    timingType: 'section',
    section: '第2セッション',
    customStart: null,
    customEnd: null,
    estMin: 60,
    actStart: null,
    actEnd: null,
    actMin: 0,
    frog: 3,
    domainMajor: 'PN1',
    domainMinor: 'AI品質工学',
    deptMajor: 'HONBU',
    deptMinor: '経営戦略部',
    projMajor: 'BIZ',
    projMinor: 'AI品質工学',
    status: 'uncompleted',
    notes: '',
    createdAt: '2026-08-17T10:00:00.000Z'
  },
  {
    id: 'T008',
    title: '新規クライアント向けキックオフ資料の構成案作成',
    bucket: 'this_week',
    label: 'p1',
    type: 'single',
    timingType: 'section',
    section: '第2セッション',
    customStart: null,
    customEnd: null,
    estMin: 45,
    actStart: null,
    actEnd: null,
    actMin: 0,
    frog: 4,
    domainMajor: 'PN2',
    domainMinor: 'ビジネス (動画編集制作)',
    deptMajor: 'HONBU',
    deptMinor: '制作部',
    projMajor: 'BIZ',
    projMinor: '初案件獲得',
    status: 'uncompleted',
    notes: '',
    createdAt: '2026-08-17T11:00:00.000Z'
  },
  {
    id: 'T009',
    title: '全自動動画生成AIパイプラインの構築（これ作ったら神！）',
    bucket: 'genius',
    label: 'p2',
    type: 'single',
    timingType: 'section',
    section: '第2セッション',
    customStart: null,
    customEnd: null,
    estMin: 120,
    actStart: null,
    actEnd: null,
    actMin: 0,
    frog: 2,
    domainMajor: 'PN1',
    domainMinor: 'AI品質工学',
    deptMajor: 'HONBU',
    deptMinor: '経営戦略部',
    projMajor: 'BIZ',
    projMinor: 'AI品質工学',
    status: 'uncompleted',
    notes: '俺サイコー！勢いづけ着火用タスク',
    createdAt: '2026-08-17T12:00:00.000Z'
  },
  {
    id: 'T010',
    title: '昔書いたSF小説・設定資料の再編集と電子書籍化検討',
    bucket: 'someday',
    label: 'p4',
    type: 'single',
    timingType: 'anytime',
    section: '第4セッション',
    customStart: null,
    customEnd: null,
    estMin: 180,
    actStart: null,
    actEnd: null,
    actMin: 0,
    frog: 1,
    domainMajor: 'PN4',
    domainMinor: 'GS',
    deptMajor: 'HONBU',
    deptMinor: 'クリエイティブ部',
    projMajor: 'LIFE',
    projMinor: '自己投資',
    status: 'uncompleted',
    notes: '',
    createdAt: '2026-08-17T12:30:00.000Z'
  }
];

// =========================================================================
// 3. Default Goals Data (Weekly, Monthly, Half-Year, 3-Year Phase)
// =========================================================================

const DEFAULT_GOALS = {
  weekly: {
    startDate: '2026-08-17',
    endDate: '2026-08-23',
    obsidianUri: '週次目標',
    lines: [
      '🔥 B社クライアント提案書の初稿完成・見積もり承認獲得',
      '🐸 朝イチ未読メール・連絡処理の毎日撃破ルーティン確立',
      '🎯 今週のタスク消化率 85% 以上を維持する',
      '🌿 1日5分以上の夜日記・感謝習慣を1日も切らさず継続',
      '💪 週末に次週のタスク棚卸し・ゾーン集中バッファを設計'
    ]
  },
  monthly: {
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    obsidianUri: '月次目標',
    lines: [
      '🌕 新規案件の受注確定（目標売上マイルストーン達成）',
      '🚀 AIエージェント業務パイプラインの本格実稼働と時間30%短縮',
      '📈 全セクションのタスク完了リズムを身体に定着させる',
      '🧘‍♂️ 睡眠スコア・朝の静寂時間のクオリティを最優先管理',
      '💡 Recent Genius Ideas から2件以上を具現化してローンチ'
    ]
  },
  half: {
    startDate: '2026-07-01',
    endDate: '2026-12-31',
    obsidianUri: 'ハーフ目標',
    lines: [
      '⚡ 安定した事業収益基盤の確立（自立型ビジネスモデルの構築）',
      '🛠️ 自社プロダクト・ツールのβ版完成とコアユーザー検証',
      '🧘 メンタル負荷・カエル撃退の自動化システムを完全運用',
      '👥 信頼できる外部パートナー・チーム連携体制の構築',
      '💰 投資・資産形成（100PayBack目標）の進捗率50%達成'
    ]
  },
  phase: {
    phaseName: '第1フェイズ：圧倒的基盤構築と自立事業化',
    startDate: '2025-01-01',
    endDate: '2027-12-31',
    obsidianUri: 'フェイズ目標',
    lines: [
      '🌌 【3年後の絶対到達地】時間と場所に縛られない自由な事業と人生の確立',
      '💎 業界内で一目置かれる独自ポジションとブランドの構築',
      '🛡️ 揺るぎない経済的自立と強固な資産防衛システムの完成',
      '❤️ 心身の最高のコンディションを維持し、毎日ワクワクして生きる',
      '🤝 価値観を共有できる仲間と共に、世の中に価値あるインパクトを残す'
    ]
  }
};

// =========================================================================
// 4. Default Interrupt Task Presets
// =========================================================================

const DEFAULT_TASK_PRESETS = [
  {
    id: 'preset_childcare',
    icon: '👶',
    title: '子ども・家族の緊急対応',
    estMin: 15,
    label: 'p3',
    frog: 2,
    domainMajor: 'PN5',
    domainMinor: '家庭・育児',
    deptMajor: 'HONBU',
    deptMinor: '総務部',
    projMajor: 'LIFE',
    projMinor: '家庭'
  },
  {
    id: 'preset_housework',
    icon: '🍲',
    title: '家事の緊急割り込み（洗濯・片付け・料理）',
    estMin: 20,
    label: 'p3',
    frog: 2,
    domainMajor: 'PN5',
    domainMinor: '家事',
    deptMajor: 'HONBU',
    deptMinor: '総務部',
    projMajor: 'LIFE',
    projMinor: '生活基盤'
  },
  {
    id: 'preset_delivery',
    icon: '📦',
    title: '宅急便・来客・郵便対応',
    estMin: 10,
    label: 'p3',
    frog: 1,
    domainMajor: 'PN5',
    domainMinor: '雑務',
    deptMajor: 'HONBU',
    deptMinor: '総務部',
    projMajor: 'LIFE',
    projMinor: '生活基盤'
  },
  {
    id: 'preset_call',
    icon: '📞',
    title: '緊急電話・重要連絡対応',
    estMin: 15,
    label: 'p1',
    frog: 3,
    domainMajor: 'PN1',
    domainMinor: '連絡',
    deptMajor: 'HONBU',
    deptMinor: '経営戦略部',
    projMajor: 'BIZ',
    projMinor: '緊急対応'
  },
  {
    id: 'preset_bug',
    icon: '🚨',
    title: '緊急バグ・システムトラブル対応',
    estMin: 30,
    label: 'p1',
    frog: 4,
    domainMajor: 'PN1',
    domainMinor: 'AI品質工学',
    deptMajor: 'HONBU',
    deptMinor: '開発部',
    projMajor: 'BIZ',
    projMinor: 'AI品質工学'
  },
  {
    id: 'preset_clean',
    icon: '🧹',
    title: 'デスク周り整理・緊急片付け',
    estMin: 15,
    label: 'p3',
    frog: 2,
    domainMajor: 'PN5',
    domainMinor: '環境整備',
    deptMajor: 'HONBU',
    deptMinor: '総務部',
    projMajor: 'LIFE',
    projMinor: '生活基盤'
  }
];

// =========================================================================
// 5. Default Core Manifesto (魂の宣誓・根本決意)
// =========================================================================

const DEFAULT_MANIFESTO = {
  title: '我が人生の絶対原則・魂の宣誓',
  motto: '“恐れを突破し、己の真価を解き放て”',
  body: `【我が人生の絶対理念】
私は、他人の引いたレールや世間の常識に自分を合わせるために生きているのではない。
自らの才能、情熱、時間を極限まで解き放ち、圧倒的な価値と自由を自らの手で創造するためにここにいる。

【不変の行動原則】
1. 恐れから逃げず、一番重いカエル（Frog）を真っ先に撃破せよ。
2. 小さなブレや脱線に囚われるな。何度でも軽やかに立ち上がり、前進せよ。
3. 計画は道具であり、主役は自分だ。自分の魂がワクワクする方角だけを見据えろ。
4. 時間は有限であり、今日という一日は二度と戻らない。命を燃やして今を生き抜け。

【ブレた時に立ち戻る原点】
・完璧を求めるな、前進を求めよ。
・迷ったら、最も勇気が必要な道を選べ。
・自分を信じろ。未来は今この瞬間の決断から作られる。`
};
